language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9"
- sudo apt-get install -y -qq lcov curl docker
- sudo ./scripts/run-containers.sh 10.1.1.1

script:
- mkdir build && cd build && cmake -DTESTS=ON .. && make && sed -i 's/^gcov/gcov-4.9/' coveralls-upload && ./bin/runTests && ./coveralls-upload
