language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9"
- sudo apt-get install -y -qq lcov curl

script:
- mkdir build && cd build && cmake -DCOVERALLS=ON .. && make && ./bin/runTests && ./coveralls-upload
